# Generated by Django 2.1.2 on 2019-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('community', models.CharField(default='public', max_length=200)),
                ('vendor', models.CharField(choices=[['APC', 'APC']], default='APC', max_length=20)),
            ],
        ),
    ]
