# Generated by Django 2.1.4 on 2019-08-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
