# Generated by Django 3.0.3 on 2020-07-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsinfo', '0002_ups_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_time', models.DateTimeField(auto_now=True)),
                ('ups', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upsinfo.Ups')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('event', models.TextField()),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsinfo.Ups')),
            ],
        ),
    ]
