# Generated by Django 3.1.8 on 2022-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsinfo', '0004_ups_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ups',
            name='vendor',
            field=models.CharField(choices=[['Generic', 'RFC 1628'], ['APC', 'APC'], ['Eaton', 'Eaton'], ['APCSmartConnect', 'APC Smart Connect'], ['EPPC', 'PowerWalker EPPC']], default='Generic', max_length=20),
        ),
    ]
